### ISSUE TITLE
Uses the Dan Handler.

### ISSUE THREAD

**Issue by SunburntRock89** [StupidDan/AphelionBot#5]
Please just stop trying to use it, Dan. It's a piece of dog shit. It's even worse the way you do it.

**Comment by StupidDan** [comment]
screw u

**Comment by SunburntRock89** [comment]
~~Are you too stupid to implement it?~~

**Comment by StupidDan** [comment]
Probably.

**Comment by SunburntRock89** [comment]
or at least fix the Dan handler

**Comment by StupidDan** [comment]
But it works lol

**Comment by SunburntRock89** [comment]
Working or not, it's a piece of shit

**Comment by SunburntRock89** [comment]
Also, I like that your strike command never actually logs anything.

**Comment by StupidDan** [comment]
Me too.
